# in this yaml you should add dependencies that are not included in the python packages
# (or that you want to install anyways such as torch to install cuda w/ conda)
# also make sure to install the local packages with the "-e" prefix
# to create an environment: conda env create -f environment.yaml
# to update: conda env update -f environment.yaml
name: airo-drake
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy==1.26.4
    - pytest
    - pre-commit
    - mypy
    - "airo-typing @ git+https://github.com/airo-ugent/airo-mono@main#subdirectory=airo-typing"
    - -e .
